// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ============================================================
  // 🌐 WEB Configuration
  // ============================================================
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiz9NK2cRfODt_CSOE1DrMHKm6Mb32NTE',
    appId: '1:82975842404:web:YOUR_WEB_APP_ID_HERE',
    messagingSenderId: '82975842404',
    projectId: 'diysocialapp',
    authDomain: 'diysocialapp.firebaseapp.com',
    storageBucket: 'diysocialapp.firebasestorage.app',
  );

  // ============================================================
  // 🤖 ANDROID Configuration (Your existing config)
  // ============================================================
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiz9NK2cRfODt_CSOE1DrMHKm6Mb32NTE',
    appId: '1:82975842404:android:50bd01c01d339366963f71',
    messagingSenderId: '82975842404',
    projectId: 'diysocialapp',
    storageBucket: 'diysocialapp.firebasestorage.app',
  );

  // ============================================================
  // 🍎 iOS Configuration
  // ============================================================
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiz9NK2cRfODt_CSOE1DrMHKm6Mb32NTE',
    appId: '1:82975842404:ios:YOUR_IOS_APP_ID_HERE',
    messagingSenderId: '82975842404',
    projectId: 'diysocialapp',
    storageBucket: 'diysocialapp.firebasestorage.app',
    iosBundleId: 'com.example.diySocialApp',
  );

  // ============================================================
  // 🖥️ macOS Configuration
  // ============================================================
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiz9NK2cRfODt_CSOE1DrMHKm6Mb32NTE',
    appId: '1:82975842404:ios:YOUR_MACOS_APP_ID_HERE',
    messagingSenderId: '82975842404',
    projectId: 'diysocialapp',
    storageBucket: 'diysocialapp.firebasestorage.app',
    iosBundleId: 'com.example.diySocialApp',
  );

  // ============================================================
  // 🪟 Windows Configuration
  // ============================================================
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiz9NK2cRfODt_CSOE1DrMHKm6Mb32NTE',
    appId: '1:82975842404:web:YOUR_WINDOWS_APP_ID_HERE',
    messagingSenderId: '82975842404',
    projectId: 'diysocialapp',
    authDomain: 'diysocialapp.firebaseapp.com',
    storageBucket: 'diysocialapp.firebasestorage.app',
  );

  // ============================================================
  // 🐧 Linux Configuration
  // ============================================================
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCiz9NK2cRfODt_CSOE1DrMHKm6Mb32NTE',
    appId: '1:82975842404:web:YOUR_LINUX_APP_ID_HERE',
    messagingSenderId: '82975842404',
    projectId: 'diysocialapp',
    authDomain: 'diysocialapp.firebaseapp.com',
    storageBucket: 'diysocialapp.firebasestorage.app',
  );

}